# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Rohan Chikkam
tagline:          'Portfolio'
description:      'Discrete Mathematics Student at the University of Warwick. DIMAP and Cybersecurity Enthusiast.'
url:              http://rchikkam.co.uk
baseurl:          /

author:
  name:           'Rohan Chikkam'
  url:            https://rchikkam.co.uk

gems: [jekyll-paginate]
paginate:         5
paginate_path: "page:num"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/chikkamrohan
